server:
  port: 8088

  loggin:
    level:
      org.springframework: debug

spring:
  messages:
    basename: messages
  security:
    user:
      name: username
      password: passw0rd
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb # not found 에러로 인하여 url 추가




management:
  endpoints:
    web:
      exposure:
        include: "*"
