server:
  port: 8088

  loggin:
    level:
      org.springframework: debug

spring:
  messages:
    basename: messages
  security:
    user:
      name: username
      password: passw0rd
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
